package treeni.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treeni.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.01.06 11:42:10 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LiikeTest {



  // Generated by ComTest BEGIN
  /** testAnna146 */
  @Test
  public void testAnna146() {    // Liike: 146
    Liike liik = new Liike(); 
    liik.parse("  1  |  2  | Pystypunnerrus  |  3  |  8  |  30  "); 
    assertEquals("From: Liike line: 149", "1", liik.anna(0)); 
    assertEquals("From: Liike line: 150", "2", liik.anna(1)); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** 
   * testClone172 
   * @throws CloneNotSupportedException when error
   */
  @Test
  public void testClone172() throws CloneNotSupportedException {    // Liike: 172
    Liike liike = new Liike(); 
    liike.parse("  1  |  2  | Pystypunnerrus  |  3  |  8  |  30  "); 
    Liike kopio = liike.clone(); 
    assertEquals("From: Liike line: 177", liike.toString(), kopio.toString()); 
    liike.parse("  2  |  12  | Kyykky  |  3  |  6  |  80  "); 
    assertEquals("From: Liike line: 179", false, kopio.toString().equals(liike.toString())); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse207 */
  @Test
  public void testParse207() {    // Liike: 207
    Liike liike = new Liike(); 
    liike.parse("  1  |  2  | Pystypunnerrus  |  3  |  8  |  30  "); 
    assertEquals("From: Liike line: 210", 2, liike.getLiikeNro()); 
    assertEquals("From: Liike line: 211", "1|2|Pystypunnerrus|3|8|30.0", liike.toString()); 
    liike.kirjaa(); 
    int n = liike.getTreeniNro(); 
    liike.parse(""+(n+20)); 
    liike.kirjaa(); 
    assertEquals("From: Liike line: 216", n+20+1, liike.getTreeniNro()); 
    assertEquals("From: Liike line: 217", "" + (n+20+1) + "|2|Pystypunnerrus|3|8|30.0", liike.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString232 */
  @Test
  public void testToString232() {    // Liike: 232
    Liike liike = new Liike(); 
    liike.parse("  1  |  2  | Pystypunnerrus  |  3  |  8  |  30  "); 
    assertEquals("From: Liike line: 235", "1|2|Pystypunnerrus|3|8|30.0", liike.toString()); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testKirjaa256 */
  @Test
  public void testKirjaa256() {    // Liike: 256
    Liike liike1 = new Liike(); 
    assertEquals("From: Liike line: 258", 0, liike1.getTreeniNro()); 
    liike1.kirjaa(); 
    Liike liike2 = new Liike(); 
    liike2.kirjaa(); 
    int n1 = liike1.getTreeniNro(); 
    int n2 = liike2.getTreeniNro(); 
    assertEquals("From: Liike line: 264", n2 - 1, n1); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta305 */
  @Test
  public void testAseta305() {    // Liike: 305
    Liike liike = new Liike(); 
    assertEquals("From: Liike line: 307", null, liike.aseta(2, "Dippi")); 
    assertEquals("From: Liike line: 308", null, liike.aseta(5, "30")); 
  } // Generated by ComTest END
}