package treeni.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treeni.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.11.30 13:22:34 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LiikeTest {



  // Generated by ComTest BEGIN
  /** testKirjaa52 */
  @Test
  public void testKirjaa52() {    // Liike: 52
    Liike liike1 = new Liike(); 
    assertEquals("From: Liike line: 54", 0, liike1.getLiikeNro()); 
    liike1.kirjaa(); 
    Liike liike2 = new Liike(); 
    liike2.kirjaa(); 
    int n1 = liike1.getLiikeNro(); 
    int n2 = liike2.getLiikeNro(); 
    assertEquals("From: Liike line: 60", n2 - 1, n1); 
  } // Generated by ComTest END
}