package treeni.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treeni.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.11.30 14:51:19 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LiikkeetTest {
    //
}