package treeni.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treeni.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.12.21 15:01:23 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class LiikkeetTest {
    //

}