package treeni.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treeni.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.12.06 23:13:45 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class SuoritusTest {



  // Generated by ComTest BEGIN
  /** testKirjaa48 */
  @Test
  public void testKirjaa48() {    // Suoritus: 48
    Suoritus treeni1 = new Suoritus(); 
    assertEquals("From: Suoritus line: 50", 0, treeni1.getTreeniNro()); 
    treeni1.kirjaa(); 
    Suoritus treeni2 = new Suoritus(); 
    treeni2.kirjaa(); 
    int tunnus1 = treeni1.getTreeniNro(); 
    int tunnus2 = treeni2.getTreeniNro(); 
    assertEquals("From: Suoritus line: 56", tunnus1 + 1, tunnus2); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString100 */
  @Test
  public void testToString100() {    // Suoritus: 100
    Suoritus suoritus = new Suoritus(); 
    suoritus.parse(" 3 |  1  |  3"); 
    assertEquals("From: Suoritus line: 103", true, suoritus.toString().startsWith("3|1|3|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse121 */
  @Test
  public void testParse121() {    // Suoritus: 121
    Suoritus suoritus = new Suoritus(); 
    suoritus.parse(" 3 |  1  |  3"); 
    assertEquals("From: Suoritus line: 124", 3, suoritus.getTreeniNro()); 
    assertEquals("From: Suoritus line: 125", true, suoritus.toString().startsWith("3|1|3|")); 
    suoritus.kirjaa(); 
    int n = suoritus.getTreeniNro(); 
    suoritus.parse(""+(n+20)); 
    suoritus.kirjaa(); 
    assertEquals("From: Suoritus line: 131", n+20+1, suoritus.getTreeniNro()); 
  } // Generated by ComTest END
}