package treeni.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treeni.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2022.11.07 21:21:49 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class SuorituksetTest {



  // Generated by ComTest BEGIN
  /** 
   * testLisaa29 
   * @throws SailoException when error
   */
  @Test
  public void testLisaa29() throws SailoException {    // Suoritukset: 29
    Suoritukset suoritukset = new Suoritukset(); 
    Suoritus treeni1 = new Suoritus(), treeni2 = new Suoritus(); 
    assertEquals("From: Suoritukset line: 33", 0, suoritukset.getLkm()); 
    suoritukset.lisaa(treeni1); assertEquals("From: Suoritukset line: 34", 1, suoritukset.getLkm()); 
    suoritukset.lisaa(treeni2); assertEquals("From: Suoritukset line: 35", 2, suoritukset.getLkm()); 
    suoritukset.lisaa(treeni1); assertEquals("From: Suoritukset line: 36", 3, suoritukset.getLkm()); 
    assertEquals("From: Suoritukset line: 37", treeni1, suoritukset.anna(0)); 
    assertEquals("From: Suoritukset line: 38", treeni2, suoritukset.anna(1)); 
    assertEquals("From: Suoritukset line: 39", treeni1, suoritukset.anna(2)); 
    assertEquals("From: Suoritukset line: 40", false, suoritukset.anna(1) == treeni1); 
    assertEquals("From: Suoritukset line: 41", true, suoritukset.anna(1) == treeni2); 
    try {
    assertEquals("From: Suoritukset line: 42", treeni1, suoritukset.anna(3)); 
    fail("Suoritukset: 42 Did not throw IndexOutOfBoundsException");
    } catch(IndexOutOfBoundsException _e_){ _e_.getMessage(); }
    suoritukset.lisaa(treeni1); assertEquals("From: Suoritukset line: 43", 4, suoritukset.getLkm()); 
    suoritukset.lisaa(treeni1); assertEquals("From: Suoritukset line: 44", 5, suoritukset.getLkm()); 
    try {
    suoritukset.lisaa(treeni1); 
    fail("Suoritukset: 45 Did not throw SailoException");
    } catch(SailoException _e_){ _e_.getMessage(); }
  } // Generated by ComTest END
}