package treeni.test;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import treeni.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.01.06 22:03:59 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class SuoritusTest {



  // Generated by ComTest BEGIN
  /** testKirjaa51 */
  @Test
  public void testKirjaa51() {    // Suoritus: 51
    Suoritus treeni1 = new Suoritus(); 
    assertEquals("From: Suoritus line: 53", 0, treeni1.getTreeniNro()); 
    treeni1.kirjaa(); 
    Suoritus treeni2 = new Suoritus(); 
    treeni2.kirjaa(); 
    int tunnus1 = treeni1.getTreeniNro(); 
    int tunnus2 = treeni2.getTreeniNro(); 
    assertEquals("From: Suoritus line: 59", tunnus1 + 1, tunnus2); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testAseta176 */
  @Test
  public void testAseta176() {    // Suoritus: 176
    Suoritus suoritus = new Suoritus(); 
    assertEquals("From: Suoritus line: 178", null, suoritus.aseta(1, "12.1.2022")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testToString261 */
  @Test
  public void testToString261() {    // Suoritus: 261
    Suoritus suoritus = new Suoritus(); 
    suoritus.parse(" 3 |  1  |  3"); 
    assertEquals("From: Suoritus line: 264", true, suoritus.toString().startsWith("3|1|3|")); 
  } // Generated by ComTest END


  // Generated by ComTest BEGIN
  /** testParse282 */
  @Test
  public void testParse282() {    // Suoritus: 282
    Suoritus suoritus = new Suoritus(); 
    suoritus.parse(" 3 |  1  |  3"); 
    assertEquals("From: Suoritus line: 285", 3, suoritus.getTreeniNro()); 
    assertEquals("From: Suoritus line: 286", true, suoritus.toString().startsWith("3|1|3|")); 
    suoritus.kirjaa(); 
    int n = suoritus.getTreeniNro(); 
    suoritus.parse(""+(n+20)); 
    suoritus.kirjaa(); 
    assertEquals("From: Suoritus line: 292", n+20+1, suoritus.getTreeniNro()); 
  } // Generated by ComTest END
}