package treeni.test;
// Generated by ComTest BEGIN
import java.util.*;
import static org.junit.Assert.*;
import org.junit.*;
import treeni.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2023.01.07 19:13:54 // Generated by ComTest
 *
 */
@SuppressWarnings({ "all" })
public class TreeniTest {
    //



  // Generated by ComTest BEGIN
  /** testAnnaLiikkeet105 */
  @Test
  public void testAnnaLiikkeet105() {    // Treeni: 105
    Treeni treeni = new Treeni(); 
    Suoritus suoritus1 = new Suoritus(), suoritus2 = new Suoritus(), suoritus3 = new Suoritus(); 
    suoritus1.kirjaa(); suoritus2.kirjaa(); suoritus3.kirjaa(); 
    int id1 = suoritus1.getTreeniNro(); 
    int id2 = suoritus2.getTreeniNro(); 
    Liike dippi11 = new Liike(id1); treeni.lisaa(dippi11); 
    Liike dippi12 = new Liike(id1); treeni.lisaa(dippi12); 
    Liike dippi21 = new Liike(id2); treeni.lisaa(dippi21); 
    Liike dippi22 = new Liike(id2); treeni.lisaa(dippi22); 
    Liike dippi23 = new Liike(id2); treeni.lisaa(dippi23); 
    List<Liike> loytyneet; 
    loytyneet = treeni.annaLiikkeet(suoritus3); 
    assertEquals("From: Treeni line: 120", 0, loytyneet.size()); 
    loytyneet = treeni.annaLiikkeet(suoritus1); 
    assertEquals("From: Treeni line: 122", 2, loytyneet.size()); 
    assertEquals("From: Treeni line: 123", true, loytyneet.get(0) == dippi11); 
    assertEquals("From: Treeni line: 124", true, loytyneet.get(1) == dippi12); 
    loytyneet = treeni.annaLiikkeet(suoritus2); 
    assertEquals("From: Treeni line: 126", 3, loytyneet.size()); 
    assertEquals("From: Treeni line: 127", true, loytyneet.get(0) == dippi21); 
  } // Generated by ComTest END
}